"""Advisory system — governance recommendations from policy evaluation.

Advisories are generated by evaluating ontologia governance policies
against live system state.  Each advisory is a structured recommendation
that can be acknowledged, dismissed, or acted upon.

Storage: ~/.organvm/advisories.jsonl (append-only)
"""

from __future__ import annotations

import hashlib
import json
import logging
from dataclasses import asdict, dataclass, field
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


def _advisories_path() -> Path:
    return Path.home() / ".organvm" / "advisories.jsonl"


@dataclass
class Advisory:
    """A governance recommendation generated by policy evaluation."""

    advisory_id: str
    policy_id: str
    action: str
    entity_id: str
    entity_name: str
    description: str
    severity: str  # "info" / "warning" / "critical"
    timestamp: str
    evidence: dict[str, Any] = field(default_factory=dict)
    acknowledged: bool = False

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Advisory:
        return cls(
            advisory_id=data.get("advisory_id", ""),
            policy_id=data.get("policy_id", ""),
            action=data.get("action", ""),
            entity_id=data.get("entity_id", ""),
            entity_name=data.get("entity_name", ""),
            description=data.get("description", ""),
            severity=data.get("severity", "info"),
            timestamp=data.get("timestamp", ""),
            evidence=data.get("evidence", {}),
            acknowledged=data.get("acknowledged", False),
        )


def _make_advisory_id(policy_id: str, entity_id: str) -> str:
    """Deterministic advisory ID from policy + entity for deduplication."""
    raw = f"{policy_id}:{entity_id}"
    return hashlib.sha256(raw.encode()).hexdigest()[:12]


def _severity_from_action(action: str) -> str:
    """Map policy action to severity level."""
    critical = {"flag", "deprecate"}
    warning = {"promote", "merge", "notify"}
    if action in critical:
        return "critical" if action == "deprecate" else "warning"
    if action in warning:
        return "info"
    return "info"


def check_snapshot_staleness(
    snapshot_path: Path,
    max_age_hours: int = 48,
) -> Advisory | None:
    """Check if system-snapshot.json is stale or missing."""
    now = datetime.now(timezone.utc)

    if not snapshot_path.is_file():
        return Advisory(
            advisory_id=_make_advisory_id("snapshot-staleness", "system"),
            policy_id="snapshot-staleness",
            action="flag",
            entity_id="system",
            entity_name="system-snapshot.json",
            description="System snapshot not found. Run `organvm refresh`.",
            severity="warning",
            timestamp=now.isoformat(),
        )

    try:
        data = json.loads(snapshot_path.read_text())
        generated_at = data.get("generated_at", "")
        if not generated_at:
            raise ValueError("No generated_at field")
        gen_dt = datetime.fromisoformat(generated_at)
        age = now - gen_dt
        if age > timedelta(hours=max_age_hours):
            days = age.days
            return Advisory(
                advisory_id=_make_advisory_id("snapshot-staleness", "system"),
                policy_id="snapshot-staleness",
                action="flag",
                entity_id="system",
                entity_name="system-snapshot.json",
                description=(
                    f"System snapshot is {days} days stale. "
                    f"Run `organvm refresh` or trigger CI workflow."
                ),
                severity="warning",
                timestamp=now.isoformat(),
                evidence={
                    "generated_at": generated_at,
                    "age_hours": int(age.total_seconds() / 3600),
                },
            )
    except (json.JSONDecodeError, ValueError, TypeError):
        return Advisory(
            advisory_id=_make_advisory_id("snapshot-staleness", "system"),
            policy_id="snapshot-staleness",
            action="flag",
            entity_id="system",
            entity_name="system-snapshot.json",
            description="System snapshot is malformed. Run `organvm refresh`.",
            severity="warning",
            timestamp=now.isoformat(),
        )

    return None


def _build_repo_state(repo_dict: dict[str, Any]) -> dict[str, Any]:
    """Build entity state dict from registry repo data for policy evaluation."""
    last_val = repo_dict.get("last_validated", "")
    is_stale = False
    if last_val:
        try:
            val_dt = datetime.fromisoformat(last_val)
            is_stale = (datetime.now(timezone.utc) - val_dt) > timedelta(days=30)
        except (ValueError, TypeError):
            pass

    return {
        "promotion_status": repo_dict.get("promotion_status", ""),
        "ci_workflow": bool(repo_dict.get("ci_workflow")),
        "platinum_status": bool(repo_dict.get("platinum_status")),
        "implementation_status": repo_dict.get("implementation_status", ""),
        "is_stale": is_stale,
        "last_validated": last_val,
        "lifecycle": "ACTIVE",
        # Fields checked by non-repo-scoped policies — safe defaults
        "is_orphan": False,
        "incoming_relations": 0,
        "cluster_size": 0,
        "cohesion": 0.0,
        "has_active_dependents": False,
    }


def _build_inference_context(
    workspace: Path | None = None,
) -> dict[str, dict[str, Any]]:
    """Build per-entity inference context from ontologia analysis.

    Runs inference once and returns a lookup mapping entity IDs to
    structural properties needed by governance policies:
    - is_orphan, incoming_relations, cluster_size, cohesion

    Returns empty dict on any failure (fail-safe).
    """
    try:
        from organvm_engine.pulse.inference_bridge import run_inference

        summary = run_inference(workspace)
        ctx: dict[str, dict[str, Any]] = {}

        # Mark orphans
        for eid in summary.orphaned_entities:
            ctx.setdefault(eid, {})["is_orphan"] = True

        # Mark overcoupled (high incoming relations)
        for eid in summary.overcoupled_entities:
            entry = ctx.setdefault(eid, {})
            entry["incoming_relations"] = entry.get("incoming_relations", 0) + 5

        # Mark cluster membership
        for cluster in summary.clusters:
            entity_ids = cluster.get("entity_ids", [])
            cohesion = cluster.get("cohesion", 0.0)
            size = len(entity_ids)
            for eid in entity_ids:
                entry = ctx.setdefault(eid, {})
                entry["cluster_size"] = size
                entry["cohesion"] = cohesion

        return ctx
    except Exception:
        logger.debug("Inference context build failed (non-fatal)", exc_info=True)
        return {}


def evaluate_all_policies(workspace: Path | None = None) -> list[Advisory]:
    """Evaluate default policies against live registry state.

    Returns a list of new advisories (deduplicates against existing ones).
    """
    from organvm_engine.pulse.default_policies import DEFAULT_POLICIES

    if not DEFAULT_POLICIES:
        return []

    try:
        from organvm_engine.registry.loader import load_registry
    except ImportError:
        return []

    try:
        registry = load_registry()
    except Exception:
        logger.debug("Could not load registry for policy evaluation", exc_info=True)
        return []

    # Read existing advisory IDs for deduplication
    existing_ids = {a.advisory_id for a in read_advisories(limit=500)}

    # Build inference context once for all repos
    inference_ctx = _build_inference_context(workspace)

    now = datetime.now(timezone.utc).isoformat()
    advisories: list[Advisory] = []

    # Evaluate per-repo policies
    for organ_key, organ_data in registry.get("organs", {}).items():
        for repo in organ_data.get("repositories", []):
            repo_name = repo.get("name", "")
            entity_id = f"{organ_key}/{repo_name}"
            state = _build_repo_state(repo)

            # Merge inference-derived structural data if available
            for eid, entity_data in inference_ctx.items():
                # Match by entity ID suffix (repo name) since inference uses UIDs
                if eid.endswith(repo_name) or repo_name in eid:
                    state.update(entity_data)
                    break

            for policy in DEFAULT_POLICIES:
                if policy.scope_entity_type and policy.scope_entity_type != "repo":
                    continue
                if policy.evaluate(state):
                    adv_id = _make_advisory_id(policy.policy_id, entity_id)
                    if adv_id in existing_ids:
                        continue
                    advisories.append(Advisory(
                        advisory_id=adv_id,
                        policy_id=policy.policy_id,
                        action=policy.action.value,
                        entity_id=entity_id,
                        entity_name=repo_name,
                        description=f"{policy.name}: {repo_name}",
                        severity=_severity_from_action(policy.action.value),
                        timestamp=now,
                        evidence={k: v for k, v in state.items()
                                  if v and v is not True},
                    ))

    # -----------------------------------------------------------------------
    # Metric threshold advisories — best-effort, completely optional
    # -----------------------------------------------------------------------
    try:
        from organvm_engine.pulse.metric_policies import evaluate_metric_thresholds
    except ImportError:
        pass
    else:
        try:
            from ontologia.registry.store import open_store

            store = open_store()
            obs_store = store.observation_store
            all_obs = obs_store.query()
            metric_advs = evaluate_metric_thresholds(all_obs)
            for adv in metric_advs:
                if adv.advisory_id not in existing_ids:
                    advisories.append(adv)
        except ImportError:
            logger.debug("ontologia not available for metric threshold evaluation")
        except Exception:
            logger.debug(
                "Metric threshold evaluation failed (non-fatal)", exc_info=True,
            )

    # Check snapshot staleness
    try:
        from organvm_engine.paths import corpus_dir
        snapshot_path = Path(corpus_dir()) / "system-snapshot.json"
        staleness = check_snapshot_staleness(snapshot_path)
        if staleness and staleness.advisory_id not in existing_ids:
            advisories.append(staleness)
    except Exception:
        pass

    return advisories


def store_advisories(advisories: list[Advisory]) -> None:
    """Append advisories to ~/.organvm/advisories.jsonl."""
    if not advisories:
        return
    path = _advisories_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a") as f:
        for adv in advisories:
            f.write(json.dumps(adv.to_dict(), separators=(",", ":"), default=str) + "\n")


def read_advisories(
    limit: int = 50,
    unacked_only: bool = False,
) -> list[Advisory]:
    """Read recent advisories from the JSONL store."""
    path = _advisories_path()
    if not path.is_file():
        return []

    advisories: list[Advisory] = []
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            adv = Advisory.from_dict(json.loads(line))
            if unacked_only and adv.acknowledged:
                continue
            advisories.append(adv)
        except (json.JSONDecodeError, TypeError):
            continue

    return advisories[-limit:]


def acknowledge_advisory(advisory_id: str) -> bool:
    """Mark an advisory as acknowledged by rewriting the JSONL.

    Returns True if the advisory was found and updated.
    """
    path = _advisories_path()
    if not path.is_file():
        return False

    lines = path.read_text().splitlines()
    found = False
    new_lines: list[str] = []

    for line in lines:
        line = line.strip()
        if not line:
            continue
        try:
            data = json.loads(line)
            if data.get("advisory_id") == advisory_id:
                data["acknowledged"] = True
                found = True
            new_lines.append(json.dumps(data, separators=(",", ":"), default=str))
        except (json.JSONDecodeError, TypeError):
            new_lines.append(line)

    if found:
        path.write_text("\n".join(new_lines) + "\n" if new_lines else "")

    return found
