"""Narrative testament synthesis from the trivium translation matrix.

Generates periodic narratives that synthesize the system's structural
unity — which translations are strongest, which are emerging, and
what patterns the isomorphism detection has revealed.
"""

from __future__ import annotations

from datetime import date, datetime, timezone
from pathlib import Path

from organvm_engine.trivium.dialects import (
    Dialect,
    all_dialects,
    dialect_profile,
    organ_for_dialect,
)
from organvm_engine.trivium.taxonomy import (
    TranslationTier,
    pairs_by_tier,
)
from organvm_engine.trivium.translator import (
    TranslationEvidence,
    translation_matrix,
)


def synthesize_trivium_testament(
    registry_path: Path | None = None,
    registry: dict | None = None,
) -> str:
    """Generate a Markdown narrative synthesis of cross-organ isomorphisms.

    This is the system describing its own structural unity — the philosophical
    testament that proves all organs speak the same language.
    """
    matrix = translation_matrix(
        registry_path=registry_path, registry=registry,
    )
    now = datetime.now(timezone.utc)
    today = date.today().isoformat()

    lines: list[str] = []
    lines.append("# Trivium Testament — Dialectica Universalis")
    lines.append("")
    lines.append(
        f"*Generated {today} — the system proving its own structural unity.*",
    )
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(
        "The structural isomorphism of thought, truth, and computation. "
        "Language, mathematics, and algorithms are not different disciplines; "
        "they are merely different dialects of the same underlying universal "
        "logic.",
    )
    lines.append("")

    # Dialect overview
    lines.append("## The Eight Dialects")
    lines.append("")
    lines.append(
        "| Organ | Dialect | Classical Parallel | Translation Role |",
    )
    lines.append("|-------|---------|-------------------|-----------------|")
    for d in all_dialects():
        p = dialect_profile(d)
        lines.append(
            f"| {p.organ_key} ({p.organ_name}) | {d.name} | "
            f"{p.classical_parallel} | {p.translation_role} |",
        )
    lines.append("")

    # Translation matrix summary
    lines.append("## Translation Matrix")
    lines.append("")
    lines.append(_render_matrix_summary(matrix))
    lines.append("")

    # Tier breakdown
    lines.append("## By Evidence Tier")
    lines.append("")
    for tier in TranslationTier:
        tier_pairs = pairs_by_tier(tier)
        lines.append(f"### Tier: {tier.value.title()} ({len(tier_pairs)} pairs)")
        lines.append("")
        for tp in tier_pairs:
            key = _matrix_key(tp.source, tp.target, matrix)
            ev = matrix.get(key)
            if ev and ev.correspondences:
                lines.append(
                    f"- **{organ_for_dialect(tp.source)}↔"
                    f"{organ_for_dialect(tp.target)}**: "
                    f"{len(ev.correspondences)} correspondences, "
                    f"strength {ev.aggregate_strength:.2f}",
                )
            else:
                lines.append(
                    f"- **{organ_for_dialect(tp.source)}↔"
                    f"{organ_for_dialect(tp.target)}**: {tp.description}",
                )
        lines.append("")

    # Strongest translations
    strongest = _top_pairs(matrix, n=5)
    if strongest:
        lines.append("## Strongest Translations")
        lines.append("")
        for ev in strongest:
            lines.append(
                f"1. **{ev.source_organ}↔{ev.target_organ}** "
                f"(strength {ev.aggregate_strength:.2f}): "
                f"{ev.preservation_assessment}",
            )
        lines.append("")

    # Footer
    lines.append("---")
    lines.append("")
    lines.append(
        "*Generated by `organvm trivium synthesize`. "
        "The system renders its own structural unity into experience.*",
    )
    lines.append("")
    lines.append(f"*ORGANVM TRIVIUM TESTAMENT — {now.isoformat()}*")

    return "\n".join(lines)


def render_translation_matrix_markdown(
    matrix: dict[tuple[Dialect, Dialect], TranslationEvidence],
) -> str:
    """Render the 28-pair evidence matrix as a Markdown table."""
    if not matrix:
        return "*No translation evidence collected yet.*"

    lines: list[str] = []
    lines.append(
        "| Source | Target | Correspondences | Strength | Preservation |",
    )
    lines.append("|--------|--------|-----------------|----------|--------------|")

    for (a, b), ev in sorted(
        matrix.items(),
        key=lambda x: -x[1].aggregate_strength,
    ):
        lines.append(
            f"| {organ_for_dialect(a)} | {organ_for_dialect(b)} | "
            f"{len(ev.correspondences)} | {ev.aggregate_strength:.2f} | "
            f"{ev.preservation_assessment} |",
        )

    return "\n".join(lines)


def render_dialect_portrait(dialect: Dialect) -> str:
    """Render a single dialect's self-description."""
    p = dialect_profile(dialect)
    today = date.today().isoformat()

    lines = [
        f"# Dialect Portrait: {p.organ_name} ({p.organ_key})",
        "",
        f"*Testament portrait — {today}*",
        "",
        "---",
        "",
        f"**Dialect:** {dialect.name}",
        f"**Classical Parallel:** {p.classical_parallel}",
        f"**Formal Basis:** {p.formal_basis}",
        "",
        "## Translation Role",
        "",
        p.translation_role,
        "",
        "## Description",
        "",
        p.description,
        "",
        "---",
        f"*ORGANVM TRIVIUM — Dialect {p.organ_key} — {today}*",
    ]
    return "\n".join(lines)


def write_testament(
    content: str,
    testament_dir: Path,
    period: str = "monthly",
) -> Path:
    """Write trivium testament to an explicit directory.

    The CLI command resolves the path (typically praxis-perpetua/testament/trivium/).
    This follows the network/synthesizer.py pattern.
    """
    now = datetime.now(timezone.utc)
    filename = f"{now.strftime('%Y-%m-%d')}-trivium-synthesis.md"
    out_path = testament_dir / filename
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content)
    return out_path


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _render_matrix_summary(
    matrix: dict[tuple[Dialect, Dialect], TranslationEvidence],
) -> str:
    """One-line summary of the matrix state."""
    total = len(matrix)
    with_evidence = sum(
        1 for ev in matrix.values() if ev.correspondences
    )
    total_corr = sum(
        len(ev.correspondences) for ev in matrix.values()
    )
    avg = (
        sum(ev.aggregate_strength for ev in matrix.values()) / total
        if total else 0.0
    )
    return (
        f"**{total} translation pairs** | "
        f"**{with_evidence} with empirical evidence** | "
        f"**{total_corr} total correspondences** | "
        f"**avg strength {avg:.2f}**"
    )


def _top_pairs(
    matrix: dict[tuple[Dialect, Dialect], TranslationEvidence],
    n: int = 5,
) -> list[TranslationEvidence]:
    """Return the N pairs with highest aggregate strength."""
    ranked = sorted(
        matrix.values(),
        key=lambda ev: ev.aggregate_strength,
        reverse=True,
    )
    return ranked[:n]


def _matrix_key(
    a: Dialect, b: Dialect,
    matrix: dict[tuple[Dialect, Dialect], TranslationEvidence],
) -> tuple[Dialect, Dialect]:
    """Find the correct key ordering for a pair in the matrix."""
    if (a, b) in matrix:
        return (a, b)
    if (b, a) in matrix:
        return (b, a)
    return (a, b)  # fallback
